import { catalogRepository, authRepository, cartRepository, orderRepository, adminRepository } from "./repositories.factory";
import {
  GetProductsUseCase,
  GetProductDetailUseCase,
  GetCatalogFiltersUseCase,
  GetPromotionsUseCase,
} from "@/application/use-cases/catalog.use-cases";
import {
  LoginUseCase,
  RegisterUseCase,
  LogoutUseCase,
  GetProfileUseCase,
  UpdateProfileUseCase,
  RequestPasswordResetUseCase,
  VerifyOtpUseCase,
  ConfirmPasswordResetUseCase,
} from "@/application/use-cases/auth.use-cases";
import {
  GetCartUseCase,
  AddCartItemUseCase,
  RemoveCartItemUseCase,
  CreateOrderUseCase,
  GetOrdersUseCase,
  GetOrderDetailUseCase,
  UploadComprobanteUseCase,
  GetActiveSellersUseCase,
  GetShippingZonesUseCase,
} from "@/application/use-cases/order.use-cases";
import {
  UploadImageUseCase,
  CreateProductUseCase,
  UpdateProductUseCase,
  DeleteProductUseCase,
  CreateVariantUseCase,
  UpdateVariantUseCase,
  DeleteVariantUseCase,
  CreateBrandUseCase,
  UpdateBrandUseCase,
  DeleteBrandUseCase,
  GetBrandsUseCase,
  CreateCategoryUseCase,
  UpdateCategoryUseCase,
  DeleteCategoryUseCase,
  GetCategoriesUseCase,
  CreateTallaUseCase,
  UpdateTallaUseCase,
  DeleteTallaUseCase,
  GetTallasUseCase,
  GetAdminUsersUseCase,
  CreateUserAdminUseCase,
  UpdateUserAdminUseCase,
  DeleteUserAdminUseCase,
  GetPendingPaymentsUseCase,
  VerifyPaymentUseCase,
  ShipOrderUseCase,
  DeliverOrderUseCase,
  GetAdminStatsUseCase,
  GetSellerOrdersUseCase,
  GetCommissionReportUseCase,
  GetCampaignsUseCase,
  CreateCampaignUseCase,
  SendCampaignUseCase,
} from "@/application/use-cases/admin.use-cases";
import {
  GetNotificationsUseCase,
  MarkNotificationReadUseCase,
} from "@/application/use-cases/notification.use-cases";
import { notificationRepository } from "./repositories.factory";

export const useCases = {
  getProducts: new GetProductsUseCase(catalogRepository),
  getProductDetail: new GetProductDetailUseCase(catalogRepository),
  getCatalogFilters: new GetCatalogFiltersUseCase(catalogRepository),
  getPromotions: new GetPromotionsUseCase(catalogRepository),

  login: new LoginUseCase(authRepository),
  register: new RegisterUseCase(authRepository),
  logout: new LogoutUseCase(authRepository),
  getProfile: new GetProfileUseCase(authRepository),
  updateProfile: new UpdateProfileUseCase(authRepository),
  requestPasswordReset: new RequestPasswordResetUseCase(authRepository),
  verifyOtp: new VerifyOtpUseCase(authRepository),
  confirmPasswordReset: new ConfirmPasswordResetUseCase(authRepository),

  getCart: new GetCartUseCase(cartRepository),
  addCartItem: new AddCartItemUseCase(cartRepository),
  removeCartItem: new RemoveCartItemUseCase(cartRepository),
  createOrder: new CreateOrderUseCase(orderRepository),
  getOrders: new GetOrdersUseCase(orderRepository),
  getOrderDetail: new GetOrderDetailUseCase(orderRepository),
  uploadComprobante: new UploadComprobanteUseCase(orderRepository),
  getActiveSellers: new GetActiveSellersUseCase(orderRepository),
  getShippingZones: new GetShippingZonesUseCase(orderRepository),

  uploadImage: new UploadImageUseCase(adminRepository),
  createProduct: new CreateProductUseCase(adminRepository),
  updateProduct: new UpdateProductUseCase(adminRepository),
  deleteProduct: new DeleteProductUseCase(adminRepository),
  createVariant: new CreateVariantUseCase(adminRepository),
  updateVariant: new UpdateVariantUseCase(adminRepository),
  deleteVariant: new DeleteVariantUseCase(adminRepository),
  createBrand: new CreateBrandUseCase(adminRepository),
  updateBrand: new UpdateBrandUseCase(adminRepository),
  deleteBrand: new DeleteBrandUseCase(adminRepository),
  getBrands: new GetBrandsUseCase(adminRepository),
  createCategory: new CreateCategoryUseCase(adminRepository),
  updateCategory: new UpdateCategoryUseCase(adminRepository),
  deleteCategory: new DeleteCategoryUseCase(adminRepository),
  getCategories: new GetCategoriesUseCase(adminRepository),
  createTalla: new CreateTallaUseCase(adminRepository),
  updateTalla: new UpdateTallaUseCase(adminRepository),
  deleteTalla: new DeleteTallaUseCase(adminRepository),
  getTallas: new GetTallasUseCase(adminRepository),
  getAdminUsers: new GetAdminUsersUseCase(adminRepository),
  createUserAdmin: new CreateUserAdminUseCase(adminRepository),
  updateUserAdmin: new UpdateUserAdminUseCase(adminRepository),
  deleteUserAdmin: new DeleteUserAdminUseCase(adminRepository),
  getPendingPayments: new GetPendingPaymentsUseCase(adminRepository),
  verifyPayment: new VerifyPaymentUseCase(adminRepository),
  shipOrder: new ShipOrderUseCase(adminRepository),
  deliverOrder: new DeliverOrderUseCase(adminRepository),
  getAdminStats: new GetAdminStatsUseCase(adminRepository),
  getSellerOrders: new GetSellerOrdersUseCase(adminRepository),
  getCommissionReport: new GetCommissionReportUseCase(adminRepository),
  getCampaigns: new GetCampaignsUseCase(adminRepository),
  createCampaign: new CreateCampaignUseCase(adminRepository),
  sendCampaign: new SendCampaignUseCase(adminRepository),

  getNotifications: new GetNotificationsUseCase(notificationRepository),
  markNotificationRead: new MarkNotificationReadUseCase(notificationRepository),
};
